### ISSUE TITLE
HPO dies after first trial

### ISSUE THREAD

**Issue by fratajcz** [uma-pi1/kge#167]
Hi!

I have implemented and registered my own evaluation method. Training, evaluation and early stopping all work great. Now when I start an HPO, the first trial runs as expected and then dies when finishing the first or when starting the second trial. I don't know if I am missing something in the implementation of my evaluation or if the problem lies elsewhere

These are the last lines of the log including the Error Traceback:

```
[f2bd3f15] Saving checkpoint to /home/fratajcz/kge/local/experiments/20201218-165812-hpo-CxD-drkg-union-transe/00000/checkpoint_00062.pt...
[f2bd3f15] Removing old checkpoint /home/fratajcz/kge/local/experiments/20201218-165812-hpo-CxD-drkg-union-transe/00000/checkpoint_00061.pt...
[f2bd3f15] Stopping early (mrr_CxD_val did not improve over best result in the last 3 validation runs).
[a0955d4f] Best result in this training job:
[a0955d4f] Trial 00000 failed: KeyError('event')
[a0955d4f] Aborting search due to failure of trial 00000
Traceback (most recent call last):
  File "/home/fratajcz/anaconda3/envs/pygeo/bin/kge", line 33, in <module>
    sys.exit(load_entry_point('libkge', 'console_scripts', 'kge')())
  File "/home/fratajcz/kge/kge/cli.py", line 317, in main
    job.run()
  File "/home/fratajcz/kge/kge/job/job.py", line 159, in run
    result = self._run()
  File "/home/fratajcz/kge/kge/job/auto_search.py", line 160, in _run
    self.submit_task(
  File "/home/fratajcz/kge/kge/job/search.py", line 80, in submit_task
    self.ready_task_results.append(task(task_arg, device=self.free_devices[0]))
  File "/home/fratajcz/kge/kge/job/search.py", line 243, in _run_train_job
    raise e
  File "/home/fratajcz/kge/kge/job/search.py", line 221, in _run_train_job
    best["event"],
KeyError: 'event'
```

I would be very happy if you could give me some pointers.

**Comment by fratajcz** [comment]
I think I have found the Issue, I forgot to add an ```'event'``` key to the ```self.current_trace["epoch"]``` in my custom evaluation job. Started the HPO again, we'll see if it works now.

**Comment by rgemulla** [comment]
Yes, but we should also be more liberal in LibKGE. I pushed a small fix to address this.
