### ISSUE TITLE
Evaluate HPO result on test set

### ISSUE THREAD

**Issue by fratajcz** [uma-pi1/kge#171]
Hi!

Another day, another question from me :)

I was about to evaluate the best model from my hpo on the test set using the cli.

However, when i use it along the lines of ```kge test <hpo folder>``` i get the following error:
```
Loaded 19367 keys from map entity_ids
Loaded 23 keys from map relation_ids
Loaded 1516464 train triples
Loaded 96 valid triples
Loaded 96 test triples
Traceback (most recent call last):
  File "/home/fratajcz/anaconda3/envs/pygeo/bin/kge", line 33, in <module>
    sys.exit(load_entry_point('libkge', 'console_scripts', 'kge')())
  File "/home/fratajcz/kge/kge/cli.py", line 304, in main
    checkpoint = load_checkpoint(
  File "/home/fratajcz/kge/kge/util/io.py", line 38, in load_checkpoint
    raise IOError(
OSError: Specified checkpoint file local/experiments/<hpo folder>/checkpoint_best.pt does not exist.
```

On the other hand, when i use it along the lines of  ```kge test <best trial folder>``` so it finds the checkpoint_best.pt, I get the following error:
```
Traceback (most recent call last):
  File "/home/fratajcz/anaconda3/envs/pygeo/bin/kge", line 33, in <module>
    sys.exit(load_entry_point('libkge', 'console_scripts', 'kge')())
  File "/home/fratajcz/kge/kge/cli.py", line 299, in main
    dataset = Dataset.create(config)
  File "/home/fratajcz/kge/kge/dataset.py", line 107, in create
    dataset.entity_ids()
  File "/home/fratajcz/kge/kge/dataset.py", line 460, in entity_ids
    return self.map_indexes(indexes, "entity_ids")
  File "/home/fratajcz/kge/kge/dataset.py", line 565, in map_indexes
    map_ = self.load_map(key, as_list=True)
  File "/home/fratajcz/kge/kge/dataset.py", line 281, in load_map
    self.ensure_available(key)
  File "/home/fratajcz/kge/kge/dataset.py", line 84, in ensure_available
    raise IOError(
OSError: File /home/fratajcz/kge/data/./entity_ids.del for key entity_ids could not be found
```

When I combine the two and give it the hpo folder and manually specify the checkpoint_best.pt it should use, along the lines of ```kge  test <hpo folder> --checkpoint <best trial folder>/checkpoint_best.pt``` I get the following error:

```
Loaded 19367 keys from map entity_ids
Loaded 23 keys from map relation_ids
Loaded 1516464 train triples
Loaded 96 valid triples
Loaded 96 test triples
Traceback (most recent call last):
  File "/home/fratajcz/anaconda3/envs/pygeo/bin/kge", line 33, in <module>
    sys.exit(load_entry_point('libkge', 'console_scripts', 'kge')())
  File "/home/fratajcz/kge/kge/cli.py", line 307, in main
    job = Job.create_from(
  File "/home/fratajcz/kge/kge/job/job.py", line 119, in create_from
    model = KgeModel.create_from(
  File "/home/fratajcz/kge/kge/model/kge_model.py", line 590, in create_from
    model.load(checkpoint["model"])
  File "/home/fratajcz/kge/kge/model/kge_model.py", line 120, in load
    self.load_state_dict(state_dict)
  File "/home/fratajcz/anaconda3/envs/pygeo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TransE:
        size mismatch for _entity_embedder._embeddings.weight: copying a param with shape torch.Size([19367, 256]) from checkpoint, the shape in current model is torch.Size([19367, 100]).
        size mismatch for _relation_embedder._embeddings.weight: copying a param with shape torch.Size([23, 256]) from checkpoint, the shape in current model is torch.Size([23, 100]).
```

I dont get where it has the dimension 100 from since the hpo only optimized between 64, 128 and 256. 

Is there a way for me to use the cli for testing or do i have to manually evaluate it?

Thanks!

**Comment by rgemulla** [comment]
First, you can only test on outputs of train jobs (trials, output = a model), but not on the output of search jobs (output = a hyperparameter setting). So you need to run ```kge test <best trial folder>```.

Try ```kge dump config checkpoint_best.pt``` or ```kge dump config --full checkpoint_best.pt``` to see if there is a problem with the config in the checkpoint. Looks like the dataset / dataset folders are flawed.

**Comment by samuelbroscheit** [comment]
Is this issue resolved from your side and can be closed @fratajcz ?

**Comment by fratajcz** [comment]
I used my own evaluation script to check test set performance and thus didnt further look into the solution you proposed. Still thanks for answering.
