### ISSUE TITLE
Confusing errors when running ConvE

### ISSUE THREAD

**Issue by fratajcz** [uma-pi1/kge#180]
Hi!

I just started experimenting with ConvE and I noticed some difficulties.

1. When I dont define any parameters for the model in the yaml file, it chooses an invalid dimension:
```
Traceback (most recent call last):
  File "/home/fratajcz/anaconda3/envs/pygeo/bin/kge", line 33, in <module>
    sys.exit(load_entry_point('libkge', 'console_scripts', 'kge')())
  File "/home/fratajcz/kge/kge/cli.py", line 316, in main
    job = Job.create(config, dataset)
  File "/home/fratajcz/kge/kge/job/job.py", line 82, in create
    return TrainingJob.create(
  File "/home/fratajcz/kge/kge/job/train.py", line 124, in create
    return TrainingJobKvsAll(
  File "/home/fratajcz/kge/kge/job/train.py", line 626, in __init__
    super().__init__(
  File "/home/fratajcz/kge/kge/job/train.py", line 70, in __init__
    self.model: KgeModel = KgeModel.create(config, dataset)
  File "/home/fratajcz/kge/kge/model/kge_model.py", line 496, in create
    model = getattr(module, class_name)(
  File "/home/fratajcz/kge/kge/model/conve.py", line 121, in __init__
    scorer=ConvEScorer(config, dataset, self.configuration_key),
  File "/home/fratajcz/kge/kge/model/conve.py", line 36, in __init__
    raise Exception(
Exception: Aspect ratio 2 does not produce 2D integers for dimension 100.
```
2. Then i went ahead and set the dimension to 200, which produced another error:
```
Loaded 19364 keys from map entity_ids
Loaded 44 keys from map relation_ids
Loaded 3033222 train triples
Loaded 188 valid triples
Loaded 188 test triples
[8c6e469d] Initializing 1-to-N training job...
[8c6e469d]   128582 distinct sp pairs in train
[8c6e469d]   128582 distinct po pairs in train
[8c6e469d] Starting training...
[8c6e469d] Starting epoch 1...
Traceback (most recent call last):
  File "/home/fratajcz/anaconda3/envs/pygeo/bin/kge", line 33, in <module>
    sys.exit(load_entry_point('libkge', 'console_scripts', 'kge')())
  File "/home/fratajcz/kge/kge/cli.py", line 317, in main
    job.run()
  File "/home/fratajcz/kge/kge/job/job.py", line 159, in run
    result = self._run()
  File "/home/fratajcz/kge/kge/job/train.py", line 199, in _run
    trace_entry = self.run_epoch()
  File "/home/fratajcz/kge/kge/job/train.py", line 371, in run_epoch
    raise e
  File "/home/fratajcz/kge/kge/job/train.py", line 360, in run_epoch
    batch_result: TrainingJob._ProcessBatchResult = self._process_batch(
  File "/home/fratajcz/kge/kge/job/train.py", line 588, in _process_batch
    self._process_subbatch(batch_index, batch, subbatch_slice, result)
  File "/home/fratajcz/kge/kge/job/train.py", line 877, in _process_subbatch
    scores = self.model.score_po(
  File "/home/fratajcz/kge/kge/model/kge_model.py", line 730, in score_po
    return self._scorer.score_emb(s, p, o, combine="_po")
  File "/home/fratajcz/kge/kge/model/conve.py", line 77, in score_emb
    stacked_inputs = torch.cat([s_emb_2d, p_emb_2d], 2)
RuntimeError: Sizes of tensors must match except in dimension 0. Got 62 and 19364 (The offending index is 0)
```
The 19364 is the number of nodes, but i have no idea where that 62 comes from. 

3. When I run a negative sampling training job with the same parameters that work for TransE, ComplEx and DistMult, set the dimension to 200 and only score sp_, it still gives me the following error message:
```
Traceback (most recent call last):
  File "/home/fratajcz/anaconda3/envs/pygeo/bin/kge", line 33, in <module>
    sys.exit(load_entry_point('libkge', 'console_scripts', 'kge')())
  File "/home/fratajcz/kge/kge/cli.py", line 317, in main
    job.run()
  File "/home/fratajcz/kge/kge/job/job.py", line 159, in run
    result = self._run()
  File "/home/fratajcz/kge/kge/job/auto_search.py", line 160, in _run
    self.submit_task(
  File "/home/fratajcz/kge/kge/job/search.py", line 80, in submit_task
    self.ready_task_results.append(task(task_arg, device=self.free_devices[0]))
  File "/home/fratajcz/kge/kge/job/search.py", line 243, in _run_train_job
    raise e
  File "/home/fratajcz/kge/kge/job/search.py", line 196, in _run_train_job
    job.run()
  File "/home/fratajcz/kge/kge/job/job.py", line 159, in run
    result = self._run()
  File "/home/fratajcz/kge/kge/job/train.py", line 199, in _run
    trace_entry = self.run_epoch()
  File "/home/fratajcz/kge/kge/job/train.py", line 360, in run_epoch
    batch_result: TrainingJob._ProcessBatchResult = self._process_batch(
  File "/home/fratajcz/kge/kge/job/train.py", line 588, in _process_batch
    self._process_subbatch(batch_index, batch, subbatch_slice, result)
  File "/home/fratajcz/kge/kge/job/train.py", line 1014, in _process_subbatch
    scores[:, 0] = self.model.score_spo(
  File "/home/fratajcz/kge/kge/model/conve.py", line 140, in score_spo
    raise ValueError("ConvE can only score objects")
ValueError: ConvE can only score objects
```

at least I assume that i score only in the direction "o", since my search job's yaml only contains
```
    # Training-type specific hyperparameters
    - name: negative_sampling.num_negatives_o   #train_type: negative_sampling
      type: range                               #train_type: negative_sampling
      bounds: [1, 1000]                         #train_type: negative_sampling
      log_scale: True                           #train_type: negative_sampling
```

For now I am out of ideas how i could make this work. I still want to include ConvE in my benchmarks, though. Are there any Hints on which parameters are mandatory for ConvE and which produce errors by default?

Cheers and thanks very much again!

**Comment by rgemulla** [comment]
For 1: This is expected, the dimensions don't match for 100. Set `conve.round_dim` to `true` to let LibKGE fix this problem for you.

For 2: Hard to say. Can you post your config, ideally against the toy dataset?

For 3: You'll need to set `negative_sampling.num_samples.s` to `0` to avoid sampling subjects. Generally, though, you should use `reciprocal_relations_model` with `conve` as the base model.

**Comment by fratajcz** [comment]
For 1: Works like a charm!

For 2:

config: 
```
job.type: train
dataset.name: toy

train:
  max_epochs: 400
  auto_correct: True

valid:
  every: 2
  metric: mean_reciprocal_rank_filtered_with_test
  early_stopping:
    patience: 3

eval:
  batch_size: 128

entity_ranking:
  filter_with_test: True
  hits_at_k_s: [1, 3, 5, 10, 20]

model: conve
conve.round_dim: true
negative_sampling.num_samples.s: 0
```

Error:
```
Loading configuration of dataset toy...
Loaded 280 keys from map entity_ids
Loaded 112 keys from map relation_ids
Loaded 4565 train triples
Loaded 109 valid triples
Loaded 152 test triples
[f466eeaf] Rounded embedding dimension up to 128 to match given aspect ratio.
[f466eeaf] Initializing 1-to-N training job...
[f466eeaf]   1132 distinct sp pairs in train
[f466eeaf]   817 distinct po pairs in train
[f466eeaf] Starting training...
[f466eeaf] Starting epoch 1...
Traceback (most recent call last):
  File "/home/fratajcz/anaconda3/envs/pygeo/bin/kge", line 33, in <module>
    sys.exit(load_entry_point('libkge', 'console_scripts', 'kge')())
  File "/home/fratajcz/kge/kge/cli.py", line 317, in main
    job.run()
  File "/home/fratajcz/kge/kge/job/job.py", line 159, in run
    result = self._run()
  File "/home/fratajcz/kge/kge/job/train.py", line 199, in _run
    trace_entry = self.run_epoch()
  File "/home/fratajcz/kge/kge/job/train.py", line 371, in run_epoch
    raise e
  File "/home/fratajcz/kge/kge/job/train.py", line 360, in run_epoch
    batch_result: TrainingJob._ProcessBatchResult = self._process_batch(
  File "/home/fratajcz/kge/kge/job/train.py", line 588, in _process_batch
    self._process_subbatch(batch_index, batch, subbatch_slice, result)
  File "/home/fratajcz/kge/kge/job/train.py", line 877, in _process_subbatch
    scores = self.model.score_po(
  File "/home/fratajcz/kge/kge/model/kge_model.py", line 730, in score_po
    return self._scorer.score_emb(s, p, o, combine="_po")
  File "/home/fratajcz/kge/kge/model/conve.py", line 77, in score_emb
    stacked_inputs = torch.cat([s_emb_2d, p_emb_2d], 2)
RuntimeError: Sizes of tensors must match except in dimension 0. Got 40 and 280 (The offending index is 0)
```

For 3: Also works, as you can see in the config above. However, how do i do as you said, use ```reciprocal_relations_model``` with ConvE as base model? I mean, what do i have to put into the config?

**Comment by rgemulla** [comment]
2: You are using KvsAll, which also scores subjects unless you set `KvsAll.query_types._po` to false. I pushed a small change to make the ConvE error messages more helpful.

3: See `examples/toy-conve-train.yaml`.

**Comment by fratajcz** [comment]
Thanks a lot, you are the best! But still, even when trained with Negative Sampling or the ```KvsAll.query_types._po``` set to false, the models still resists evaluation with the line i mentioned above:

```
model._scorer.score_emb(head_embeddings, relation_embeddings[0].unsqueeze(0), tail_embeddings, combine= "sp_")
```

Since I have to evaluate my models after training in a few different ways, i need to make this work. Not necessarily with this line, but some way to give the ConvE model a bunch of Subjects, Predicates and Objects and make it return the corresponding scores would be of great use. Do you have an Idea on how to go about it?

To clarify, ```head_embeddings``` is an ```n_subject_nodes```x```n_dim``` Tensor, ```relation_embeddings[0].unsqueeze(0)``` is a ```1```x```n_dim``` Tensor and ```tail_embeddings``` is a ```n_object_nodes```x```n_dim``` Tensor. DistMult, TransE and ComplEx can score with this line, which usually returns a ```n_subject_nodes * n_object_nodes```x```1``` Tensor which I then process further. 

Cheers and Thanks a lot!

**Comment by AdrianKs** [comment]
With `KvsAll.query_types._po` you managed to train by scoring in only on direction: `sp?`. But during evaluation by default you are scoring in both directions `sp?` and `?po`. To achieve this with ConvE you'll need to train a reciprocal relations model. 
You can use a reciprocal relations model by specifying these lines in your config:
```yaml
model: reciprocal_relations_model
reciprocal_relations_model.base_model.type: conve
```

This should then also allow to train by scoring in both directions again.

**Comment by fratajcz** [comment]
Hi Adrian! I did include the two lines in my config and it trains well and evaluates with KvsAll and Negative Sampling. However, when I import the model after training is done and explicitely score triples, It refuses. 

I tried to change to a higher-level method call:
```
model.score_spo(head_embeddings, relation_embeddings[0].unsqueeze(0), tail_embeddings, direction="o")
```
instead of calling the scorer directly, but this also fails with the following error message:
```
Traceback (most recent call last):
  File "/home/fratajcz/kge/evaluate_test.py", line 133, in <module>
    scores = model.score_spo(head_embeddings, relation_embeddings[0].unsqueeze(0), tail_embeddings, direction="o")
  File "/home/fratajcz/kge/kge/model/reciprocal_relations_model.py", line 58, in score_spo
    return super().score_spo(s, p, o, "o")
  File "/home/fratajcz/kge/kge/model/kge_model.py", line 685, in score_spo
    return self._scorer.score_emb(s, p, o, combine="spo").view(-1)
  File "/home/fratajcz/kge/kge/model/conve.py", line 75, in score_emb
    s_emb_2d = s_emb[:, 1:].view(-1, 1, int(self.emb_height), int(self.emb_width))
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```
I don't know what this does differently than what happens during training/evaluation, i.e in kge/job/entity_ranking.py:
```
o_true_scores = self.model.score_spo(s, p, o, "o").view(-1)
```

**Comment by rgemulla** [comment]
Your input tensors do not seem to be contiguous. Did you try adding `.contiguous()` to the inputs to score_spo?

**Comment by fratajcz** [comment]
It didnt change the error for ```model.score_spo()```, but it did for ```model._scorer.score_emb()```:
```
Traceback (most recent call last):
  File "/home/fratajcz/kge/evaluate_test.py", line 136, in <module>
    scores = model._scorer.score_emb(head_embeddings.contiguous(), relation_embeddings[i].unsqueeze(0).contiguous(), tail_embeddings.contiguous(), combine= "sp_")
  File "/home/fratajcz/kge/kge/model/conve.py", line 77, in score_emb
    stacked_inputs = torch.cat([s_emb_2d, p_emb_2d], 2)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 136 and 1 in dimension 0 (The offending index is 1)
```
The dimension of the Input Tensors are ```torch.Size([136, 289])``` (subject), ```torch.Size([1, 289])```(predicate) ```torch.Size([1503, 289])``` (object). So this time it got 2 lines further, managed to convoloute the tensors but then got stuck stacking them. 

Btw thanks for always helping me out, I know you wouldn't have to do this.

**Comment by AdrianKs** [comment]
I think you're input tensors are incorrect. the function `model.score_spo` takes as input 3 tensors of dim `[n,1]` containing the ids.
Have a look at the documentation of the function:
https://github.com/uma-pi1/kge/blob/2de6ad66d7676fc68bfb9998305ec61b683b9aa1/kge/model/kge_model.py#L664
```
        Compute scores for a set of triples.
        `s`, `p`, and `o` are vectors of common size :math:`n`, holding the indexes of
        the subjects, relations, and objects to score.
        `direction` may influence how scores are computed. For most models, this setting
        has no meaning. For reciprocal relations, direction must be either `"s"` or
        `"o"` (depending on what is predicted).
        Returns a vector of size :math:`n`, in which the :math:`i`-th entry holds the
        score of triple :math:`(s_i, p_i, o_i)`.
```

**Comment by rgemulla** [comment]
The tensors need to be 1D, not 0D.

**Comment by fratajcz** [comment]
Ahh okay, here we go. This works, so now i only have to make the tensors with all the n x m combinations of subjects and objects myself and feed it into score_spo. Thanks and sorry for taking up all your day 👍
